### ISSUE TITLE
Create article detailing ada lovelace's work

### ISSUE THREAD

**Issue by dyyyl** [rajsandhu/ada-lovelace#5]

**Comment by rajsandhu** [comment]
I'll regurgitate text about her from https://en.wikipedia.org/wiki/Ada_Lovelace . The license on the text is https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License . To use the text, I'll need to adopt the CC license, which will be no problem for me to do.
